version: '3.8'

services:
  weather-mcp:
    build: .
    container_name: weather-mcp-server
    restart: unless-stopped
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
    command: python server.py
